### ISSUE TITLE
建议使用 Silk.NET 完整替代 OpenTK

### ISSUE THREAD

**Issue by qian-o** [Richasy/mpv-winui#1]
在这个项目中，OpenTK 的主要目的是创建一个不可见的窗口和 WGL 扩展的包装器。
但在最新版的 Silk.NET 已经有了完整的工具链，建议使用该包来简化代码和打包体积。

我曾在几个月前更新了 WinUI 的示例，可以参考下。
https://github.com/qian-o/SilkRenderer

**Comment by LazyCuteLion** [comment]
尝试了一下，没能成功。
问题出在“GetProcAddress”方法，不知道Silk.Net中，对应的OpenTK.IBindingsContext是啥，改为使用“GL.Context”（.GetProcAddress），然后没能呈现画面。

**Comment by LazyCuteLion** [comment]
> 尝试了一下，没能成功。 问题出在“GetProcAddress”方法，不知道Silk.Net中，对应的OpenTK.IBindingsContext是啥，改为使用“GL.Context”（.GetProcAddress），然后没能呈现画面。

呃，似乎问题出在于FrameBuffer，重新copy了“Begin和End”2个方法的代码，就可以了。
就是CPU占用率挺高，可能是OpenGL与D3D11的处理产生了消耗。
